apiVersion: apps/v1
kind: Deployment
metadata:
  name: authv2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authv2
  template:
    metadata:
      labels:
        app: authv2
    spec:
      containers:
        - name: authv2
          image: akronborn/authv2
          env:
            - name: MONGO_URI
              value: "mongodb://authv2-mongo-srv:27017/authv2"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: authv2
  ports:
    - name: authv2
      protocol: TCP
      port: 3000
      targetPort: 3000
